#!/bin/bash


MOBILECONFIG=$(cat << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>PayloadContent</key>
    <array>
        <dict>
            <key>FilterType</key>
            <string>BuiltIn</string>
            <key>DenyListURLs</key>
            <array>
                <string>0.0.0.0</string>
                <string>10.0.0.0</string>
                <string>10.0.0.1</string>
                <string>10.0.0.2</string>
                <string>127.0.0.1</string>
                <string>172.16.0.0</string>
                <string>172.16.0.1</string>
                <string>172.16.0.2</string>
                <string>172.17.0.0</string>
                <string>172.17.0.1</string>
                <string>172.17.0.2</string>
                <string>172.18.0.0</string>
                <string>172.18.0.1</string>
                <string>172.18.0.2</string>
                <string>172.19.0.0</string>
                <string>172.19.0.1</string>
                <string>172.19.0.2</string>
                <string>172.20.0.0</string>
                <string>172.20.0.1</string>
                <string>172.20.0.2</string>
                <string>172.21.0.0</string>
                <string>172.21.0.1</string>
                <string>172.21.0.2</string>
                <string>172.22.0.0</string>
                <string>172.22.0.1</string>
                <string>172.22.0.2</string>
                <string>172.23.0.0</string>
                <string>172.23.0.1</string>
                <string>172.23.0.2</string>
                <string>172.24.0.0</string>
                <string>172.24.0.1</string>
                <string>172.24.0.2</string>
                <string>172.25.0.0</string>
                <string>172.25.0.1</string>
                <string>172.25.0.2</string>
                <string>172.26.0.0</string>
                <string>172.26.0.1</string>
                <string>172.26.0.2</string>
                <string>172.27.0.0</string>
                <string>172.27.0.1</string>
                <string>172.27.0.2</string>
                <string>172.28.0.0</string>
                <string>172.28.0.1</string>
                <string>172.28.0.2</string>
                <string>172.29.0.0</string>
                <string>172.29.0.1</string>
                <string>172.29.0.2</string>
                <string>172.30.0.0</string>
                <string>172.30.0.1</string>
                <string>172.30.0.2</string>
                <string>172.31.0.0</string>
                <string>172.31.0.1</string>
                <string>172.31.0.2</string>
                <string>169.254.0.0</string>
                <string>169.254.0.1</string>
                <string>169.254.0.2</string>
                <string>192.0.0.0</string>
                <string>192.0.0.1</string>
                <string>192.0.0.2</string>
                <string>255.255.255.255</string>
                <string>local</string>
                <string>localhost</string>
                <string>lan</string>
                <string>internal</string>
                <string>private</string>
                <string>test</string>
                <string>invalid</string>
                <string>home</string>
                <string>example</string>
                <string>arpa</string>
                <string>*.local</string>
                <string>*.localhost</string>
                <string>*.lan</string>
                <string>*.internal</string>
                <string>*.private</string>
                <string>*.test</string>
                <string>*.invalid</string>
                <string>*.home</string>
                <string>*.example</string>
                <string>*.arpa</string>
                <string>6tisch.arpa</string>
                <string>as112.arpa</string>
                <string>e164.arpa</string>
                <string>eap-noob.arpa</string>
                <string>eap.arpa</string>
                <string>home.arpa</string>
                <string>in-addr-servers.arpa</string>
                <string>in-addr.arpa</string>
                <string>ip6-servers.arpa</string>
                <string>ip6.arpa</string>
                <string>ipv4only.arpa</string>
                <string>iris.arpa</string>
                <string>ns.arpa</string>
                <string>resolver.arpa</string>
                <string>service.arpa</string>
                <string>uri.arpa</string>
                <string>urn.arpa</string>
                <string>*.6tisch.arpa</string>
                <string>*.as112.arpa</string>
                <string>*.e164.arpa</string>
                <string>*.eap-noob.arpa</string>
                <string>*.eap.arpa</string>
                <string>*.home.arpa</string>
                <string>*.in-addr-servers.arpa</string>
                <string>*.in-addr.arpa</string>
                <string>*.ip6-servers.arpa</string>
                <string>*.ip6.arpa</string>
                <string>*.ipv4only.arpa</string>
                <string>*.iris.arpa</string>
                <string>*.ns.arpa</string>
                <string>*.resolver.arpa</string>
                <string>*.service.arpa</string>
                <string>*.uri.arpa</string>
                <string>*.urn.arpa</string>
                <string>orange</string>
                <string>*.orange</string>
                <string>acte</string>
                <string>*.acte</string>
                <string>world</string>
                <string>*.world</string>
                <string>orange.acte</string>
                <string>orange.world</string>
                <string>*.orange.acte</string>
                <string>*.orange.world</string>
                <string>ofnew</string>
                <string>*.ofnew</string>
                <string>ofnew.fr</string>
                <string>*.ofnew.fr</string>
                <string>sl2sfr</string>
                <string>wapsfr</string>
                <string>mmsdebitel</string>
                <string>*.sl2sfr</string>
                <string>*.wapsfr</string>
                <string>*.mmsdebitel</string>
                <string>free.fr</string>
                <string>*.free.fr</string>
                <string>free</string>
                <string>mmsfree</string>
                <string>*.free</string>
                <string>*.mmsfree</string>
                <string>mmsbouygtel</string>
                <string>*.mmsbouygtel</string>
                <string>mmsbouygtel.com</string>
                <string>*.mmsbouygtel.com</string>
                <string>bouyguestelecom</string>
                <string>*.bouyguestelecom</string>
                <string>bouyguestelecom.fr</string>
                <string>*.bouyguestelecom.fr</string>
                <string>3gppnetwork</string>
                <string>*.3gppnetwork</string>
                <string>3gppnetwork.org</string>
                <string>*.3gppnetwork.org</string>
                <string>*.pub.3gppnetwork.org</string>
                <string>mnc.mcc.3gppnetwork.org</string>
                <string>*.mnc.mcc.3gppnetwork.org</string>
                <string>*.mcc.3gppnetwork.org</string>
                <string>700.207.imsi.3gppnetwork.org</string>
                <string>701.207.imsi.3gppnetwork.org</string>
                <string>702.207.imsi.3gppnetwork.org</string>
                <string>703.207.imsi.3gppnetwork.org</string>
                <string>704.207.imsi.3gppnetwork.org</string>
                <string>705.207.imsi.3gppnetwork.org</string>
                <string>706.207.imsi.3gppnetwork.org</string>
                <string>707.207.imsi.3gppnetwork.org</string>
                <string>708.207.imsi.3gppnetwork.org</string>
                <string>709.207.imsi.3gppnetwork.org</string>
                <string>710.207.imsi.3gppnetwork.org</string>
                <string>711.207.imsi.3gppnetwork.org</string>
                <string>712.207.imsi.3gppnetwork.org</string>
                <string>713.207.imsi.3gppnetwork.org</string>
                <string>714.207.imsi.3gppnetwork.org</string>
                <string>715.207.imsi.3gppnetwork.org</string>
                <string>716.207.imsi.3gppnetwork.org</string>
                <string>717.207.imsi.3gppnetwork.org</string>
                <string>718.207.imsi.3gppnetwork.org</string>
                <string>719.207.imsi.3gppnetwork.org</string>
                <string>720.207.imsi.3gppnetwork.org</string>
                <string>00.208.imsi.3gppnetwork.org</string>
                <string>01.208.imsi.3gppnetwork.org</string>
                <string>02.208.imsi.3gppnetwork.org</string>
                <string>03.208.imsi.3gppnetwork.org</string>
                <string>04.208.imsi.3gppnetwork.org</string>
                <string>05.208.imsi.3gppnetwork.org</string>
                <string>06.208.imsi.3gppnetwork.org</string>
                <string>07.208.imsi.3gppnetwork.org</string>
                <string>08.208.imsi.3gppnetwork.org</string>
                <string>09.208.imsi.3gppnetwork.org</string>
                <string>10.208.imsi.3gppnetwork.org</string>
                <string>11.208.imsi.3gppnetwork.org</string>
                <string>12.208.imsi.3gppnetwork.org</string>
                <string>13.208.imsi.3gppnetwork.org</string>
                <string>14.208.imsi.3gppnetwork.org</string>
                <string>15.208.imsi.3gppnetwork.org</string>
                <string>16.208.imsi.3gppnetwork.org</string>
                <string>17.208.imsi.3gppnetwork.org</string>
                <string>18.208.imsi.3gppnetwork.org</string>
                <string>19.208.imsi.3gppnetwork.org</string>
                <string>20.208.imsi.3gppnetwork.org</string>
                <string>21.208.imsi.3gppnetwork.org</string>
                <string>22.208.imsi.3gppnetwork.org</string>
                <string>23.208.imsi.3gppnetwork.org</string>
                <string>24.208.imsi.3gppnetwork.org</string>
                <string>25.208.imsi.3gppnetwork.org</string>
                <string>26.208.imsi.3gppnetwork.org</string>
                <string>27.208.imsi.3gppnetwork.org</string>
                <string>28.208.imsi.3gppnetwork.org</string>
                <string>29.208.imsi.3gppnetwork.org</string>
                <string>30.208.imsi.3gppnetwork.org</string>
                <string>31.208.imsi.3gppnetwork.org</string>
                <string>32.208.imsi.3gppnetwork.org</string>
                <string>33.208.imsi.3gppnetwork.org</string>
                <string>34.208.imsi.3gppnetwork.org</string>
                <string>35.208.imsi.3gppnetwork.org</string>
                <string>36.208.imsi.3gppnetwork.org</string>
                <string>37.208.imsi.3gppnetwork.org</string>
                <string>38.208.imsi.3gppnetwork.org</string>
                <string>39.208.imsi.3gppnetwork.org</string>
                <string>40.208.imsi.3gppnetwork.org</string>
                <string>41.208.imsi.3gppnetwork.org</string>
                <string>42.208.imsi.3gppnetwork.org</string>
                <string>43.208.imsi.3gppnetwork.org</string>
                <string>44.208.imsi.3gppnetwork.org</string>
                <string>45.208.imsi.3gppnetwork.org</string>
                <string>46.208.imsi.3gppnetwork.org</string>
                <string>47.208.imsi.3gppnetwork.org</string>
                <string>48.208.imsi.3gppnetwork.org</string>
                <string>49.208.imsi.3gppnetwork.org</string>
                <string>50.208.imsi.3gppnetwork.org</string>
                <string>51.208.imsi.3gppnetwork.org</string>
                <string>52.208.imsi.3gppnetwork.org</string>
                <string>53.208.imsi.3gppnetwork.org</string>
                <string>54.208.imsi.3gppnetwork.org</string>
                <string>55.208.imsi.3gppnetwork.org</string>
                <string>56.208.imsi.3gppnetwork.org</string>
                <string>57.208.imsi.3gppnetwork.org</string>
                <string>58.208.imsi.3gppnetwork.org</string>
                <string>59.208.imsi.3gppnetwork.org</string>
                <string>60.208.imsi.3gppnetwork.org</string>
                <string>61.208.imsi.3gppnetwork.org</string>
                <string>62.208.imsi.3gppnetwork.org</string>
                <string>63.208.imsi.3gppnetwork.org</string>
                <string>64.208.imsi.3gppnetwork.org</string>
                <string>65.208.imsi.3gppnetwork.org</string>
                <string>66.208.imsi.3gppnetwork.org</string>
                <string>67.208.imsi.3gppnetwork.org</string>
                <string>68.208.imsi.3gppnetwork.org</string>
                <string>69.208.imsi.3gppnetwork.org</string>
                <string>70.208.imsi.3gppnetwork.org</string>
                <string>71.208.imsi.3gppnetwork.org</string>
                <string>72.208.imsi.3gppnetwork.org</string>
                <string>73.208.imsi.3gppnetwork.org</string>
                <string>74.208.imsi.3gppnetwork.org</string>
                <string>75.208.imsi.3gppnetwork.org</string>
                <string>76.208.imsi.3gppnetwork.org</string>
                <string>77.208.imsi.3gppnetwork.org</string>
                <string>78.208.imsi.3gppnetwork.org</string>
                <string>79.208.imsi.3gppnetwork.org</string>
                <string>80.208.imsi.3gppnetwork.org</string>
                <string>81.208.imsi.3gppnetwork.org</string>
                <string>82.208.imsi.3gppnetwork.org</string>
                <string>83.208.imsi.3gppnetwork.org</string>
                <string>84.208.imsi.3gppnetwork.org</string>
                <string>85.208.imsi.3gppnetwork.org</string>
                <string>86.208.imsi.3gppnetwork.org</string>
                <string>87.208.imsi.3gppnetwork.org</string>
                <string>88.208.imsi.3gppnetwork.org</string>
                <string>89.208.imsi.3gppnetwork.org</string>
                <string>90.208.imsi.3gppnetwork.org</string>
                <string>91.208.imsi.3gppnetwork.org</string>
                <string>92.208.imsi.3gppnetwork.org</string>
                <string>93.208.imsi.3gppnetwork.org</string>
                <string>94.208.imsi.3gppnetwork.org</string>
                <string>95.208.imsi.3gppnetwork.org</string>
                <string>96.208.imsi.3gppnetwork.org</string>
                <string>97.208.imsi.3gppnetwork.org</string>
                <string>98.208.imsi.3gppnetwork.org</string>
                <string>99.208.imsi.3gppnetwork.org</string>
                <string>100.208.imsi.3gppnetwork.org</string>
                <string>500.208.imsi.3gppnetwork.org</string>
                <string>670.208.imsi.3gppnetwork.org</string>
                <string>700.208.imsi.3gppnetwork.org</string>
                <string>701.208.imsi.3gppnetwork.org</string>
                <string>702.208.imsi.3gppnetwork.org</string>
                <string>703.208.imsi.3gppnetwork.org</string>
                <string>704.208.imsi.3gppnetwork.org</string>
                <string>705.208.imsi.3gppnetwork.org</string>
                <string>706.208.imsi.3gppnetwork.org</string>
                <string>707.208.imsi.3gppnetwork.org</string>
                <string>708.208.imsi.3gppnetwork.org</string>
                <string>709.208.imsi.3gppnetwork.org</string>
                <string>710.208.imsi.3gppnetwork.org</string>
                <string>711.208.imsi.3gppnetwork.org</string>
                <string>712.208.imsi.3gppnetwork.org</string>
                <string>713.208.imsi.3gppnetwork.org</string>
                <string>714.208.imsi.3gppnetwork.org</string>
                <string>715.208.imsi.3gppnetwork.org</string>
                <string>716.208.imsi.3gppnetwork.org</string>
                <string>717.208.imsi.3gppnetwork.org</string>
                <string>718.208.imsi.3gppnetwork.org</string>
                <string>719.208.imsi.3gppnetwork.org</string>
                <string>720.208.imsi.3gppnetwork.org</string>
                <!-- epdg.epc -->
                <string>epdg.epc.mnc700.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc701.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc702.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc703.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc704.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc705.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc706.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc707.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc708.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc709.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc710.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc711.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc712.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc713.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc714.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc715.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc716.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc717.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc718.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc719.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc720.mcc207.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc00.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc01.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc02.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc03.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc04.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc05.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc06.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc07.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc08.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc09.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc10.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc11.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc12.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc13.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc14.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc15.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc16.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc17.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc18.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc19.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc20.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc21.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc22.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc23.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc24.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc25.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc26.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc27.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc28.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc29.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc30.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc31.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc32.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc33.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc34.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc35.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc36.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc37.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc38.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc39.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc40.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc41.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc42.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc43.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc44.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc45.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc46.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc47.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc48.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc49.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc51.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc52.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc53.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc54.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc55.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc56.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc57.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc58.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc59.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc60.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc61.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc62.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc63.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc64.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc65.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc66.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc67.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc68.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc69.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc70.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc71.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc72.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc73.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc74.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc75.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc76.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc77.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc78.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc79.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc80.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc81.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc82.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc83.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc84.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc85.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc86.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc87.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc88.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc89.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc90.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc91.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc92.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc93.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc94.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc95.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc96.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc97.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc98.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc99.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc100.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc500.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc670.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc700.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc701.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc702.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc703.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc704.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc705.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc706.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc707.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc708.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc709.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc710.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc711.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc712.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc713.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc714.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc715.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc716.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc717.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc718.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc719.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc720.mcc208.pub.3gppnetwork.org</string>
                <!-- config.rcs -->
                <string>config.rcs.mnc700.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc701.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc702.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc703.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc704.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc705.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc706.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc707.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc708.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc709.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc710.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc711.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc712.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc713.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc714.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc715.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc716.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc717.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc718.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc719.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc720.mcc207.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc00.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc01.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc02.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc03.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc04.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc05.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc06.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc07.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc08.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc09.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc10.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc11.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc12.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc13.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc14.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc15.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc16.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc17.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc18.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc19.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc20.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc21.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc22.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc23.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc24.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc25.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc26.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc27.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc28.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc29.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc30.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc31.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc32.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc33.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc34.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc35.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc36.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc37.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc38.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc39.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc40.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc41.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc42.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc43.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc44.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc45.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc46.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc47.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc48.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc49.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc50.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc51.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc52.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc53.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc54.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc55.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc56.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc57.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc58.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc59.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc60.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc61.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc62.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc63.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc64.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc65.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc66.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc67.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc68.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc69.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc70.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc71.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc72.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc73.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc74.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc75.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc76.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc77.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc78.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc79.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc80.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc81.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc82.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc83.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc84.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc85.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc86.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc87.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc88.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc89.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc90.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc91.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc92.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc93.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc94.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc95.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc96.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc97.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc98.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc99.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc100.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc500.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc670.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc700.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc701.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc702.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc703.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc704.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc705.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc706.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc707.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc708.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc709.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc710.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc711.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc712.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc713.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc714.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc715.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc716.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc717.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc718.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc719.mcc208.pub.3gppnetwork.org</string>
                <string>config.rcs.mnc720.mcc208.pub.3gppnetwork.org</string>
                <!-- *.epc -->
                <string>*.epc.mnc700.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc701.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc702.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc703.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc704.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc705.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc706.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc707.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc708.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc709.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc710.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc711.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc712.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc713.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc714.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc715.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc716.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc717.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc718.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc719.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc720.mcc207.pub.3gppnetwork.org</string>
                <string>*.epc.mnc00.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc01.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc02.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc03.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc04.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc05.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc06.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc07.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc08.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc09.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc10.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc11.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc12.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc13.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc14.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc15.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc16.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc17.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc18.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc19.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc20.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc21.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc22.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc23.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc24.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc25.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc26.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc27.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc28.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc29.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc30.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc31.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc32.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc33.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc34.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc35.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc36.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc37.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc38.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc39.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc40.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc41.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc42.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc43.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc44.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc45.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc46.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc47.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc48.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc49.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc51.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc52.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc53.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc54.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc55.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc56.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc57.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc58.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc59.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc60.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc61.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc62.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc63.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc64.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc65.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc66.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc67.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc68.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc69.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc70.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc71.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc72.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc73.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc74.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc75.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc76.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc77.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc78.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc79.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc80.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc81.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc82.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc83.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc84.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc85.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc86.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc87.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc88.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc89.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc90.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc91.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc92.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc93.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc94.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc95.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc96.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc97.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc98.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc99.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc100.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc500.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc670.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc700.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc701.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc702.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc703.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc704.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc705.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc706.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc707.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc708.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc709.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc710.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc711.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc712.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc713.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc714.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc715.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc716.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc717.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc718.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc719.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc720.mcc208.pub.3gppnetwork.org</string>
                <!-- *.rcs -->
                <string>*.rcs.mnc700.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc701.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc702.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc703.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc704.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc705.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc706.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc707.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc708.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc709.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc710.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc711.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc712.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc713.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc714.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc715.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc716.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc717.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc718.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc719.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc720.mcc207.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc00.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc01.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc02.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc03.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc04.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc05.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc06.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc07.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc08.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc09.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc10.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc11.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc12.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc13.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc14.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc15.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc16.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc17.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc18.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc19.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc20.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc21.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc22.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc23.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc24.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc25.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc26.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc27.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc28.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc29.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc30.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc31.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc32.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc33.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc34.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc35.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc36.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc37.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc38.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc39.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc40.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc41.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc42.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc43.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc44.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc45.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc46.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc47.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc48.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc49.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc51.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc52.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc53.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc54.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc55.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc56.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc57.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc58.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc59.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc60.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc61.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc62.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc63.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc64.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc65.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc66.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc67.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc68.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc69.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc70.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc71.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc72.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc73.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc74.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc75.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc76.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc77.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc78.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc79.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc80.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc81.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc82.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc83.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc84.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc85.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc86.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc87.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc88.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc89.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc90.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc91.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc92.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc93.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc94.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc95.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc96.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc97.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc98.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc99.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc100.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc500.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc670.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc700.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc701.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc702.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc703.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc704.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc705.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc706.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc707.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc708.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc709.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc710.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc711.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc712.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc713.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc714.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc715.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc716.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc717.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc718.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc719.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc720.mcc208.pub.3gppnetwork.org</string>
                <!-- * -->
                <string>*.mnc700.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc701.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc702.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc703.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc704.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc705.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc706.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc707.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc708.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc709.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc710.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc711.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc712.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc713.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc714.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc715.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc716.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc717.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc718.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc719.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc720.mcc207.pub.3gppnetwork.org</string>
                <string>*.mnc00.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc01.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc02.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc03.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc04.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc05.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc06.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc07.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc08.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc09.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc10.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc11.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc12.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc13.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc14.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc15.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc16.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc17.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc18.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc19.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc20.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc21.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc22.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc23.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc24.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc25.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc26.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc27.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc28.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc29.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc30.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc31.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc32.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc33.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc34.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc35.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc36.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc37.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc38.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc39.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc40.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc41.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc42.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc43.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc44.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc45.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc46.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc47.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc48.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc49.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc51.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc52.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc53.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc54.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc55.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc56.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc57.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc58.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc59.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc60.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc61.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc62.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc63.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc64.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc65.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc66.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc67.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc68.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc69.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc70.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc71.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc72.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc73.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc74.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc75.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc76.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc77.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc78.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc79.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc80.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc81.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc82.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc83.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc84.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc85.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc86.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc87.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc88.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc89.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc90.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc91.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc92.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc93.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc94.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc95.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc96.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc97.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc98.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc99.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc100.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc500.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc670.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc700.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc701.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc702.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc703.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc704.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc705.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc706.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc707.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc708.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc709.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc710.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc711.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc712.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc713.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc714.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc715.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc716.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc717.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc718.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc719.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc720.mcc208.pub.3gppnetwork.org</string>

                <string>50144.208.imsi.3gppnetwork.org</string>
                <string>50164.208.imsi.3gppnetwork.org</string>
                <string>50168.208.imsi.3gppnetwork.org</string>
                <string>50169.208.imsi.3gppnetwork.org</string>
                <string>50176.208.imsi.3gppnetwork.org</string>
                <string>50177.208.imsi.3gppnetwork.org</string>
                <string>50192.208.imsi.3gppnetwork.org</string>
                <string>50193.208.imsi.3gppnetwork.org</string>
                <string>50194.208.imsi.3gppnetwork.org</string>
                <string>50244.208.imsi.3gppnetwork.org</string>
                <string>50268.208.imsi.3gppnetwork.org</string>
                <string>50277.208.imsi.3gppnetwork.org</string>
                <string>50357.208.imsi.3gppnetwork.org</string>
                <string>50359.208.imsi.3gppnetwork.org</string>
                <string>50387.208.imsi.3gppnetwork.org</string>
                <string>50430.208.imsi.3gppnetwork.org</string>
                <string>50484.208.imsi.3gppnetwork.org</string>
                <string>50531.208.imsi.3gppnetwork.org</string>
                <string>50549.208.imsi.3gppnetwork.org</string>
                <string>50591.208.imsi.3gppnetwork.org</string>
                <string>50631.208.imsi.3gppnetwork.org</string>
                <string>50644.208.imsi.3gppnetwork.org</string>
                <string>50692.208.imsi.3gppnetwork.org</string>
                <string>50778.208.imsi.3gppnetwork.org</string>
                <string>50876.208.imsi.3gppnetwork.org</string>
                <string>50877.208.imsi.3gppnetwork.org</string>
                <string>50935.208.imsi.3gppnetwork.org</string>
                <string>50967.208.imsi.3gppnetwork.org</string>
                <string>50975.208.imsi.3gppnetwork.org</string>
                <string>51075.208.imsi.3gppnetwork.org</string>
                <string>51094.208.imsi.3gppnetwork.org</string>
                <string>epdg.epc.mnc50144.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50164.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50168.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50169.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50176.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50177.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50192.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50193.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50194.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50244.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50268.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50277.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50357.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50359.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50387.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50430.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50484.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50531.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50549.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50591.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50631.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50644.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50692.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50778.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50876.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50877.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50935.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50967.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc50975.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc51075.mcc208.pub.3gppnetwork.org</string>
                <string>epdg.epc.mnc51094.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50144.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50164.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50168.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50169.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50176.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50177.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50192.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50193.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50194.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50244.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50268.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50277.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50357.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50359.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50387.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50430.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50484.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50531.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50549.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50591.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50631.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50644.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50692.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50778.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50876.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50877.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50935.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50967.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc50975.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc51075.mcc208.pub.3gppnetwork.org</string>
                <string>*.epc.mnc51094.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50144.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50164.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50168.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50169.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50176.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50177.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50192.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50193.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50194.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50244.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50268.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50277.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50357.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50359.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50387.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50430.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50484.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50531.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50549.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50591.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50631.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50644.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50692.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50778.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50876.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50877.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50935.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50967.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc50975.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc51075.mcc208.pub.3gppnetwork.org</string>
                <string>*.rcs.mnc51094.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50144.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50164.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50168.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50169.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50176.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50177.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50192.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50193.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50194.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50244.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50268.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50277.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50357.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50359.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50387.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50430.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50484.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50531.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50549.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50591.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50631.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50644.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50692.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50778.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50876.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50877.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50935.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50967.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc50975.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc51075.mcc208.pub.3gppnetwork.org</string>
                <string>*.mnc51094.mcc208.pub.3gppnetwork.org</string>
            </array>

            <key>ContentFilterUUID</key>
            <string>00000000-0000-0000-0000-000000000000</string><!-- not supervised/working -->

            <key>PayloadDisplayName</key>
            <string>Builtin filter Settings</string>
            <key>PayloadIdentifier</key>
            <string>macosmisc.builtinfilter.settings</string>
            <key>PayloadType</key>
            <string>com.apple.webcontent-filter</string>
            <key>PayloadUUID</key>
            <string>$(uuidgen)</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
        </dict>
    </array>
    <key>PayloadDisplayName</key>
    <string>Builtin filter Profile</string>
    <key>PayloadIdentifier</key>
    <string>macosmisc.builtinfilter.profile</string>
    <key>PayloadRemovalDisallowed</key>
    <false/>
    <key>PayloadType</key>
    <string>Configuration</string>
    <key>PayloadScope</key>
    <string>System</string>
    <key>PayloadUUID</key>
    <string>$(uuidgen)</string>
    <key>PayloadVersion</key>
    <integer>1</integer>
</dict>
</plist>
EOF
)

FILEBUILTINFILTER="$HOME/Downloads/ios.builtinfilter.mobileconfig"
echo "$MOBILECONFIG" > "$FILEBUILTINFILTER"
echo "New mobileconfig: $FILEBUILTINFILTER"
