#set loginterface lo0
#set debug loud
set debug none

extif = "en0"

#set loginterface $extif
set ruleset-optimization none
set optimization normal
set block-policy drop

scrub all

table <private> const { 10/8, 172.16/12, 192.168/16 }
table <bogons> const { 0/8, 169/8, 198/8, 203/8, 224/8, 225/8, 226/8, 227/8, 228/8, 229/8, 230/8, 231/8, 232/8, 233/8, 234/8, 235/8, 236/8, 237/8, 238/8, 239/8, 240/8, 241/8, 242/8, 243/8, 244/8, 245/8, 246/8, 247/8, 248/8, 249/8, 250/8, 251/8, 252/8, 253/8, 254/8, 255/8 }
#table <dns> const { 8.8.4.4, 86.54.11.100, 86.54.11.200 }

table <porthttps> const { 18.7.29.125, 91.210.59.156, 131.188.12.211, 167.82.50.132, 136.243.18.213, 151.101.2.132, 151.101.194.132, 151.101.66.132, 151.101.130.132, 185.199.108.133, 185.199.109.133, 185.199.110.133, 185.199.111.133 }
table <portrsync> const { 131.188.12.211 }

block all
block     quick             inet6

pass out quick inet proto icmp

#### PASS QUICK
## DNS 53 user _mdnsresponder
#pass  out quick on $extif   inet   proto udp  from ($extif)                 to <dns>          port 53                      user _mdnsresponder
## DNS 443 (DoH) user _mdnsresponder (via mobileconfig) here using censurfridns.dk||uncensoreddns.org
pass  out quick on $extif   inet   proto tcp  from ($extif)                 to 89.233.43.71   port 443                     user _mdnsresponder
## DHCP user root
#pass  out quick on $extif   inet   proto udp  from 0.0.0.0 port 68 to <private> port 67 user 0 no state # @DHCP_OUT
#pass  in  quick on $extif   inet   proto udp  from <private> port 67 to any port 68 user 0 no state # @DHCP_IN

#### BLOCK QUICK
block     quick                                                             to { <private>, <bogons> }
block     quick on ! lo0    inet              from 127/8
block     quick on   lo0    inet              from <private>
block     quick on ! $extif

#### PASS
## HTTPS MAIL user 501
pass  out       on $extif   inet   proto tcp  from ($extif)                 to                 port { 443, 993, 587, 465 }  user 501
## PORT user root and user 502
pass  out       on $extif   inet   proto tcp  from ($extif)                 to { <porthttps> } port { 443 } user 0
pass  out       on $extif   inet   proto tcp  from ($extif)                 to { <porthttps> } port { 443 } user 502
pass  out       on $extif   inet   proto tcp  from ($extif)                 to { <portrsync> } port { 873 } user 0
pass  out       on $extif   inet   proto tcp  from ($extif)                 to { <portrsync> } port { 873 } user 502


## PORT IP LIST
# trac.macports.org : 136.243.18.213 (https)
# distfiles.macports.org : 151.101.2.132 151.101.194.132 151.101.66.132 151.101.130.132 (https)
# raw.githubusercontent.com : 185.199.108.133 185.199.109.133 185.199.110.133 185.199.111.133 (https)
# packages.macports.org : 167.82.50.132 (https)
# Packages (https) :
# nue.de.distfiles.macports.org
# 131.188.12.211
# cph.dk.distfiles.macports.org
# 91.210.59.156
# bos.us.distfiles.macports.org
# 18.7.29.125
# rsync.macports.org : 131.188.12.211 (rsync)